# --- App Info ---
application: chess-cf
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# --- URL Handlers ---
handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /apple-touch-icon\.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon\.png

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /assets
  static_dir: assets

- url: /_ah/spi/.*
  script: api.APPLICATION

- url: .*
  script: main.app

# --- Libraries ---
libraries:
- name: webapp2
  version: 2.5.2

- name: jinja2
  version: 2.6

- name: endpoints
  version: 1.0

# --- Services ---
inbound_services:
- warmup